### PR TITLE
Fix #272: XSS in error page

### LINKED ISSUE #269: staging: digital wallet shows wrong info
digital wallet shows wrong info - Expires [object Object] and not editable by clicking on it

staging is currently at version 0.9-beta-5.1-23-g6d068d3

see attached screen shot
screenshot from 2016-10-12 12-57-19

### LINKED ISSUE #272: security: XSS in home page
**Description**
I found a XSS vulnerability in the home page. Here is the attack link
https://itsyou.online/error%3CBODY%20ONLOAD=%22alert(window.cookies)%22%3E

**Actual result**
screenshot from 2016-10-20 11-15-24

As you can see, We can load the user cookies. With some evil script, Attacker can hack the user accounts. 

Hint:
You have to use firefox to fire it.

### PR DESCRIPTION
**Pull request by LeeSmet**
Fix #269: digital wallet shows wrong info

Updated api documentation style

### CODE REVIEW

File: siteservice/service.go [hunk 1]
```diff
@@ -171,6 +172,24 @@ func (service *Service) ErrorPage(w http.ResponseWriter, request *http.Request)
 		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
 		return
 	}
+
+	// check if the error is a number to prevent XSS attacks
+	errorcode, err := strconv.Atoi(errornumber)
+	if err != nil {
+		log.Error("Error code could not be converted to int")
+		// The error page already loaded so we might as well use it
+		errorcode = 500;
```
Comment (robvanmieghem) [inline siteservice/service.go]: @LeeSmet can you make this a 400?

**Comment by robvanmieghem** [comment]
@LeeSmet I like the changes you made (besides a small remark I added to the commit) but it seems like something went wrong, seems like the fix for the api layout and the digital wallet address got squashed in to this fix.

**Comment by robvanmieghem** [comment]
If it is too much hassle, just squash the change from 500 to 400 and change the commitmessage to include the issue numbers of the other two fixes as well.

File: siteservice/service.go [hunk 2]
```diff
@@ -171,6 +172,24 @@ func (service *Service) ErrorPage(w http.ResponseWriter, request *http.Request)
 		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
 		return
 	}
+
+	// check if the error is a number to prevent XSS attacks
+	errorcode, err := strconv.Atoi(errornumber)
+	if err != nil {
+		log.Error("Error code could not be converted to int")
```
Comment (robvanmieghem) [inline siteservice/service.go]: Don't log this as an error since it errors should be picked up by the logging system to be looked at by ops/dev and can be triggered by anyone. Please modify to info (since this can indicate a hacking attempt)

File: siteservice/service.go [hunk 3]
```diff
@@ -171,6 +172,24 @@ func (service *Service) ErrorPage(w http.ResponseWriter, request *http.Request)
...
+		// The error page already loaded so we might as well use it
+		errorcode = 500;
+		errornumber = "500"
+	}
+
+	// check if the error code is within the accepted 4xx client or 5xx server error range
+	if errorcode > 599 || errorcode < 400 {
+		log.Error("Error code out of bounds: ", errorcode)
```
Comment (robvanmieghem) [inline siteservice/service.go]: Don't log this as an error since it errors should be picked up by the logging system to be looked at by ops/dev and can be triggered by anyone. Please modify to info (since this can indicate a hacking attempt)

**Comment by LeeSmet** [comment]
updated
