### PR TITLE
Fix password reset

### LINKED ISSUE #204: Reset password email not reseting the password
Reset password email should redirect me to enter new password but it didn't and redirect me to login page

Steps:
reset your password
click on the button/link in the reset password email

Expected:
page to enter new password

Found:
direct me to login page

### PR DESCRIPTION
**Pull request by lucasvanhalst**
Closes #204

### CODE REVIEW

File: siteservice/login.go [hunk 1]
```diff
@@ -515,7 +515,7 @@ func (service *Service) ResetPassword(w http.ResponseWriter, request *http.Reque
 	pwdMngr := password.NewManager(request)
 	token, err := pwdMngr.FindResetToken(values.Token)
 	if err != nil {
-		log.Error("Failed to find password reset token password reset - ", err)
+		log.Error("Failed to find password reset token - ", err)
```
Comment (robvanmieghem) [inline siteservice/login.go]: I would not make this an error but a debug log message. Also, it should be a 404, not a 500 I think
